<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class SportArenaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sport_arena')->insert([
            ["id" => 1, "sport_id" => 2, "arena_id" => 1],
            ["id" => 2, "sport_id" => 3, "arena_id" => 1],
            ["id" => 3, "sport_id" => 1, "arena_id" => 1],
            ["id" => 4, "sport_id" => 1, "arena_id" => 31],
            ["id" => 5, "sport_id" => 2, "arena_id" => 31],
            ["id" => 6, "sport_id" => 6, "arena_id" => 1],
            ["id" => 18, "sport_id" => 4, "arena_id" => 33],
            ["id" => 19, "sport_id" => 6, "arena_id" => 33],
            ["id" => 20, "sport_id" => 1, "arena_id" => 33],
            ["id" => 21, "sport_id" => 11, "arena_id" => 33],
            ["id" => 22, "sport_id" => 3, "arena_id" => 33],
            ["id" => 23, "sport_id" => 2, "arena_id" => 33],
            ["id" => 24, "sport_id" => 12, "arena_id" => 33],
            ["id" => 25, "sport_id" => 2, "arena_id" => 34],
            ["id" => 26, "sport_id" => 3, "arena_id" => 34],
            ["id" => 27, "sport_id" => 6, "arena_id" => 34],
            ["id" => 36, "sport_id" => 6, "arena_id" => 38],
            ["id" => 37, "sport_id" => 2, "arena_id" => 38],
            ["id" => 38, "sport_id" => 5, "arena_id" => 39],
            ["id" => 39, "sport_id" => 4, "arena_id" => 37],
            ["id" => 40, "sport_id" => 2, "arena_id" => 40],
            ["id" => 41, "sport_id" => 3, "arena_id" => 40],
            ["id" => 42, "sport_id" => 1, "arena_id" => 40],
            ["id" => 43, "sport_id" => 12, "arena_id" => 40],
            ["id" => 44, "sport_id" => 7, "arena_id" => 40],
            ["id" => 45, "sport_id" => 12, "arena_id" => 41],
            ["id" => 46, "sport_id" => 2, "arena_id" => 41],
            ["id" => 47, "sport_id" => 1, "arena_id" => 41],
            ["id" => 48, "sport_id" => 3, "arena_id" => 41],
            ["id" => 49, "sport_id" => 5, "arena_id" => 42],
            ["id" => 50, "sport_id" => 2, "arena_id" => 43],
            ["id" => 51, "sport_id" => 1, "arena_id" => 44],
            ["id" => 52, "sport_id" => 3, "arena_id" => 44],
            ["id" => 53, "sport_id" => 2, "arena_id" => 44],
            ["id" => 54, "sport_id" => 6, "arena_id" => 44],
            ["id" => 55, "sport_id" => 4, "arena_id" => 45],
            ["id" => 56, "sport_id" => 2, "arena_id" => 46],
            ["id" => 57, "sport_id" => 6, "arena_id" => 46],
            ["id" => 58, "sport_id" => 3, "arena_id" => 46],
            ["id" => 59, "sport_id" => 1, "arena_id" => 46],
            ["id" => 60, "sport_id" => 6, "arena_id" => 47],
            ["id" => 61, "sport_id" => 1, "arena_id" => 47],
            ["id" => 62, "sport_id" => 2, "arena_id" => 47],
            ["id" => 63, "sport_id" => 3, "arena_id" => 47],
            ["id" => 64, "sport_id" => 11, "arena_id" => 48],
            ["id" => 65, "sport_id" => 12, "arena_id" => 48],
            ["id" => 66, "sport_id" => 6, "arena_id" => 49],
            ["id" => 67, "sport_id" => 1, "arena_id" => 49],
            ["id" => 68, "sport_id" => 2, "arena_id" => 49],
            ["id" => 69, "sport_id" => 3, "arena_id" => 49],
            ["id" => 70, "sport_id" => 2, "arena_id" => 50],
            ["id" => 71, "sport_id" => 3, "arena_id" => 50],
            ["id" => 72, "sport_id" => 1, "arena_id" => 50],
            ["id" => 73, "sport_id" => 6, "arena_id" => 50],
            ["id" => 74, "sport_id" => 2, "arena_id" => 51],
            ["id" => 75, "sport_id" => 3, "arena_id" => 51],
            ["id" => 76, "sport_id" => 6, "arena_id" => 51],
            ["id" => 77, "sport_id" => 1, "arena_id" => 51],
            ["id" => 78, "sport_id" => 3, "arena_id" => 52],
            ["id" => 79, "sport_id" => 2, "arena_id" => 52],
            ["id" => 80, "sport_id" => 6, "arena_id" => 52],
            ["id" => 81, "sport_id" => 1, "arena_id" => 52],
            ["id" => 82, "sport_id" => 3, "arena_id" => 53],
            ["id" => 83, "sport_id" => 2, "arena_id" => 53],
            ["id" => 84, "sport_id" => 6, "arena_id" => 53],
            ["id" => 85, "sport_id" => 1, "arena_id" => 53],
            ["id" => 86, "sport_id" => 2, "arena_id" => 54],
            ["id" => 87, "sport_id" => 3, "arena_id" => 54],
            ["id" => 88, "sport_id" => 6, "arena_id" => 54],
            ["id" => 89, "sport_id" => 1, "arena_id" => 54],
            ["id" => 90, "sport_id" => 5, "arena_id" => 55],
            ["id" => 91, "sport_id" => 6, "arena_id" => 56],
            ["id" => 92, "sport_id" => 3, "arena_id" => 56],
            ["id" => 93, "sport_id" => 2, "arena_id" => 56],
            ["id" => 94, "sport_id" => 2, "arena_id" => 57],
            ["id" => 95, "sport_id" => 3, "arena_id" => 57],
            ["id" => 96, "sport_id" => 6, "arena_id" => 57],
            ["id" => 97, "sport_id" => 4, "arena_id" => 58],
            ["id" => 98, "sport_id" => 2, "arena_id" => 59],
            ["id" => 99, "sport_id" => 6, "arena_id" => 59],
            ["id" => 100, "sport_id" => 2, "arena_id" => 60],
            ["id" => 101, "sport_id" => 3, "arena_id" => 60],
            ["id" => 102, "sport_id" => 3, "arena_id" => 61],
            ["id" => 103, "sport_id" => 2, "arena_id" => 62],
            ["id" => 104, "sport_id" => 6, "arena_id" => 62],
            ["id" => 105, "sport_id" => 2, "arena_id" => 63],
            ["id" => 106, "sport_id" => 6, "arena_id" => 63],
            ["id" => 107, "sport_id" => 5, "arena_id" => 64],
            ["id" => 108, "sport_id" => 11, "arena_id" => 65],
            ["id" => 109, "sport_id" => 12, "arena_id" => 65],
            ["id" => 110, "sport_id" => 4, "arena_id" => 66],
            ["id" => 112, "sport_id" => 6, "arena_id" => 67],
            ["id" => 113, "sport_id" => 2, "arena_id" => 67],
            ["id" => 114, "sport_id" => 3, "arena_id" => 67],
            ["id" => 115, "sport_id" => 2, "arena_id" => 68],
            ["id" => 116, "sport_id" => 6, "arena_id" => 68],
            ["id" => 117, "sport_id" => 3, "arena_id" => 68],
            ["id" => 118, "sport_id" => 1, "arena_id" => 68],
        ]);
    }
}
