name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t backend .
    - name: Save Docker image to file
      run: docker save backend -o backend.tar
    - name: Copy Docker image to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: backend.tar
        target: /tmp
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: SSH into remote server and load Docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker load -i /tmp/backend.tar
          rm /tmp/backend.tar
    - name: SSH into remote server and start Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop_old_container: |
          docker rm -f backend || true
        script_start_new_container: |
          docker run -d --name backend -p 8000:8000 \
            -e APP_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'local' }} \
            -e APP_DEBUG=${{ github.ref == 'refs/heads/main' && 'false' || 'true' }} \
            -e DB_CONNECTION=pgsql \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            backend 
          docker image prune -af
